# Generated by Django 4.1.2 on 2022-10-24 10:30

import django.core.validators
from django.db import migrations, models
import new_expenses_tracker.web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='budget',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), new_expenses_tracker.web.models.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), new_expenses_tracker.web.models.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[new_expenses_tracker.web.models.MaxSizeInMbValidator(5)]),
        ),
    ]
