# Generated by Django 4.1.1 on 2022-10-11 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = ()

    operations = ()
