# Generated by Django 4.1.4 on 2022-12-20 10:16

import CarCollectionApp.web.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(validators=[CarCollectionApp.web.validators.validate_min_age_18]),
        ),
    ]
