# Generated by Django 4.1.4 on 2022-12-20 11:59

import CarCollectionApp.web.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.FloatField(validators=[CarCollectionApp.web.validators.validate_min_price]),
        ),
    ]
