# Generated by Django 4.1.1 on 2022-10-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='business_account',
            field=models.CharField(default='unknown', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_level',
            field=models.CharField(default='junior', max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='works_full_time',
            field=models.BooleanField(default=True),
        ),
    ]
