# Generated by Django 4.1.1 on 2022-10-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_employee_birth_date_employee_second_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='works_full_time',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
