# Generated by Django 4.1.1 on 2022-10-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_employee_works_full_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='works_full_time',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
