# Generated by Django 4.1.1 on 2022-10-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_employee_works_full_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='my_level',
            field=models.CharField(choices=[('jr', ' junior'), ('reg', 'regular'), ('sr', 'senior')], max_length=3, null=True),
        ),
    ]
